Feature: Command line for generating C# code from Json schema

A short summary of the feature

Scenario: Should generate c# code to console from csharp-from-json-schema verb
	Given this json schema input file with the extension "yaml"
		"""
		$schema: https://json-schema.org/draft/2020-12/schema
		id: https://drygen.net/test-json-schemas/some.json
		title: Test Schema
		type: object
		properties:
		  prop1:
		    type: string
		additionalProperties: false
		"""
	When I call the program with this command line arguments
		| Arg                     |
		| csharp-from-json-schema |
	Then I should get exit code '0'
	And console out should contain the text
		"""
		//----------------------
		// <auto-generated>
		//     Generated using the NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
		// </auto-generated>
		//----------------------
		
		
		namespace TestNameSpace
		{
		    #pragma warning disable // Disable all warnings
		
		    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.6.10.0 (Newtonsoft.Json v13.0.0.0)")]
		    public partial class TestSchema
		    {
		        [Newtonsoft.Json.JsonProperty("prop1", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
		        public string Prop1 { get; set; }
		
		
		    }
		}
		"""

Scenario: Should generate c# code to file from csharp-from-json-schema verb
	Given this json schema input file with the extension "json"
		"""
		{
			"$schema": "https://json-schema.org/draft/2020-12/schema",
			"id": "https://drygen.net/test-json-schemas/some.json",
			"title": "Test Schema",
			"type": "object",
			"properties": {
				"prop1": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
		"""
	And output is spesified as a command line argument
	When I call the program with this command line arguments
		| Arg                     |
		| csharp-from-json-schema |
	Then I should get exit code '0'
	And I should get this generated representation file
		"""
		//----------------------
		// <auto-generated>
		//     Generated using the NJsonSchema v10.6.10.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
		// </auto-generated>
		//----------------------
		
		
		namespace TestNameSpace
		{
		    #pragma warning disable // Disable all warnings
		
		    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.6.10.0 (Newtonsoft.Json v13.0.0.0)")]
		    public partial class TestSchema
		    {
		        [Newtonsoft.Json.JsonProperty("prop1", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
		        public string Prop1 { get; set; }
		
		
		    }
		}
		"""

Scenario: Should use option schema-file-format
	Given this json schema input file with the extension "json"
		"""
		$schema: https://json-schema.org/draft/2020-12/schema
		id: https://drygen.net/test-json-schemas/some.json
		title: Test Schema
		type: object
		properties:
		  prop1:
		    type: string
		additionalProperties: false
		"""
	When I call the program with this command line arguments
		| Arg                     |
		| csharp-from-json-schema |
		| --schema-file-format    |
		| <Schema file format>    |
	Then I should get exit code '<Exit code>'
Examples:
	| Schema file format | Exit code |
	| byextension        | 1         |
	| json               | 1         |
	| yaml               | 0         |


