namespace DryGen.Docs;

public static class DocsConstants
{
    public const string AutoGeneratedNotice = "Autogenerated by the Docs build step. Do not edit this file by hand, as your edits will be overwritten by the next Docs build.";
    public const string ReplaceTokenForAutoGeneratedByDocsWarning = ".!.!.replace-token-for-autogenerated-by-docs-warning.!.!.";
    public const string ReplaceTokenForAutoGeneratedByDocsSource = ".!.!.replace-token-for-autogenerated-by-docs-source.!.!.";
}
