using System;
using System.Collections.Generic;
using System.Text;

namespace DryGen.Docs
{
    public static class DocsConstants
    {
        public const string AutoGeneratedNotice = "# Autogenerated by the Docs build step. Do not edit by hand, as your edit will get overwritten by the next Docs build.";
    }
}
