using System.IO;
using System.Text;

namespace DryGen.Docs
{
    public static class ExamplesMenuGenerator
    {
        public static void Generate(TextWriter writer, string examplesTemplatesDirectory)
        {
            var sb = new StringBuilder().AppendLine(DocsConstants.AutoGeneratedNotice).AppendLine("- label: dry-gen examples").AppendLine("  items:");
            foreach (var exampleTemplateFile in Directory.GetFiles(examplesTemplatesDirectory))
            {
                var fileName = Path.GetFileNameWithoutExtension(exampleTemplateFile);
                sb.Append("  - name: ").AppendLine(fileName.Replace('_', ' ').Replace('-', ' ')).Append("    link: /examples/").AppendLine(fileName.ToLowerInvariant());
            }
            writer.Write(sb.ToString());
        }
    }
}
