using System;
using System.IO;
using System.Linq;
using System.Text;

namespace DryGen.Docs;

public static class ReleaseNotesTocGenerator
{
	public static void Generate(TextWriter writer, string releaseNotesTemplatesDirectory, DateTime today)
	{
		var releaseNoteTemplateFiles = Directory.GetFiles(releaseNotesTemplatesDirectory).OrderByDescending(x => x).ToArray();
		releaseNoteTemplateFiles.ValidateReleaseNotesFileNames(today);
		var sb = new StringBuilder().Append("# ").AppendLine(DocsConstants.AutoGeneratedNotice);
		foreach (var releaseNoteTemplateFile in releaseNoteTemplateFiles)
		{
			var fileName = Path.GetFileNameWithoutExtension(releaseNoteTemplateFile)[11..];
			sb.Append("- name: ").AppendLine(fileName.Replace("v-", "Version "))
				.Append("  href: ").Append(fileName.ToLowerInvariant()).AppendLine(".md");
		}
		writer.Write(sb.ToString());
	}
}