using System.IO;
using System.Linq;
using System.Text;

namespace DryGen.Docs;

public static class ReleaseNotesTocGenerator
{
	public static void Generate(TextWriter writer, string releaseNotesTemplatesDirectory)
	{
		var sb = new StringBuilder().Append("# ").AppendLine(DocsConstants.AutoGeneratedNotice);
		foreach (var exampleTemplateFile in Directory.GetFiles(releaseNotesTemplatesDirectory).OrderByDescending(x => x))
		{
			var fileName = Path.GetFileNameWithoutExtension(exampleTemplateFile)[11..];
			sb.Append("- name: ").AppendLine(fileName.Replace("v-", "Version "))
				.Append("  href: ").Append(fileName.ToLowerInvariant()).AppendLine(".md");
		}
		writer.Write(sb.ToString());
	}
}