using System.IO;
using System.Linq;
using System.Text;

namespace DryGen.Docs
{
    public class VerbMarkdowGenerator
    {
        public void GenerateVerbMarkdown(string verb, TextWriter writer)
        {
            var verbMetaData = verb.GetVerbMetadata();
            var sb = new StringBuilder();
            sb.AppendLine("---")
                .AppendLine(DocsConstants.AutoGeneratedNotice)
                .AppendLine("layout: page")
                .Append("title: ").AppendLine(verb)
                .Append("description: Details about the dry-gen verb ").AppendLine(verb)
                .AppendLine("show_sidebar: false")
                .AppendLine("menubar: verbs_menu")
                .AppendLine("---")
                .Append(verbMetaData.HelpText).AppendLine(" ").AppendLine()
                .AppendLine("## Options")
                .AppendLine()
                .AppendLine("|Option|Alias|Type|Description|")
                .AppendLine("|---|---|---|---|");
            foreach (var optionMetadata in verbMetaData.Options)
            {
                sb.Append('|')
                  .Append(optionMetadata.LongName.AsMarkdownTableCellValue()).Append('|')
                  .Append(optionMetadata.ShortName.AsMarkdownTableCellValue()).Append('|')
                  .Append(optionMetadata.Type.AsMarkdownTableCellValue()).Append('|')
                  .Append(optionMetadata.Description.AsMarkdownTableCellValue()).AppendLine("|");
            }
            writer.Write(sb.ToString());
        }
    }
}
