using System.IO;
using System.Linq;
using System.Text;

namespace DryGen.Docs;

public static class VerbMenuGenerator
{
    public static void Generate(TextWriter writer)
    {
        var sb = new StringBuilder();
        sb.Append("# ").AppendLine(DocsConstants.AutoGeneratedNotice).AppendLine("- name: dry-gen verbs").AppendLine("  href: index.md");
        var verbs = typeof(Generator).Assembly.GetTypes().Where(x => x.HasVerbAttribute()).Select(x => x.GetVerb());
        foreach (var verb in verbs.OrderBy(x => x))
        {
            sb.Append("- name: ").AppendLine(verb).Append("  href: ").Append(verb).AppendLine(".md");
        }
        writer.Write(sb.ToString());
    }
}