Feature: Generate release notes from templates

To be able to produce a consistent release notes layout
As a dry-gen developer
I should be able to generate the release notes header and the toc from the release templates

Scenario: Should generate table of context for release notes
	Given the release notes template folder contains these files
		| File name             |
		| 2022-09-03-v-0.7.1.md |
		| 2023-02-22-v-1.0.0.md |
		| 2024-04-07-v-1.6.2.md |
	When I generate the release notes TOC
	Then console out should contain the text
		"""
		# Autogenerated by the Docs build step. Do not edit this file by hand, as your edits will be overwritten by the next Docs build.
		- name: Version 1.6.2
		  href: v-1.6.2.md
		- name: Version 1.0.0
		  href: v-1.0.0.md
		- name: Version 0.7.1
		  href: v-0.7.1.md
		
		"""

Scenario: Should copy release notes file from template and replace header
	Given the release notes template folder contains the file "2023-10-31-v-1.3.1.Md" with content
		"""
		.!.!.replace-token-for-release-notes-header.!.!.
		Markdown content...
		"""
	When I generate the release notes file "2023-10-31-v-1.3.1.Md"
	Then the release notes folder should contain the file "v-1.3.1.md" with content
		"""
		---
		# Autogenerated by the Docs build step. Do not edit this file by hand, as your edits will be overwritten by the next Docs build.
		# Source file: "docs/templates/releases/2023-10-31-v-1.3.1.Md"
		---
		# Version 1.3.1
		**Release date 2023-10-31**
		Markdown content...
		"""
