Feature: Generate examples of usage

To be able to showcase our features
As a dry-gen developer
I should be able to generate examples by running the tool using our own codebase as the source representation

Scenario: Should generate menu for all examples
	Given the examples template folder contains these files
		| File name                           |
		| Mermaid-Class_diagrams.md           |
		| Mermaid-Er_diagrams-from-EF_Core.md |
	When I generate the examples menu
	Then console out should contain the text
		"""
		# Autogenerated by the Docs build step. Do not edit this file by hand, as your edits will be overwritten by the next Docs build.
		- label: dry-gen examples
		  items:
		  - name: Mermaid Class diagrams
		    link: /examples/mermaid-class_diagrams
		  - name: Mermaid Er diagrams from EF Core
		    link: /examples/mermaid-er_diagrams-from-ef_core
		
		"""

# We could test for the generation of more examples, but that would only make more fragile test, since the examples changes each time the examples description or the code base changes...