Feature: Generate Docs for the verbs

To be able to "live as we preach"
As a dry-gen developer
I should be able to generate documentation for each verb from the help system

Scenario: Should generate menu with all verbs
	When I generate the docs verb menu
	Then console out should contain the text
		"""
		# Autogenerated by the Docs build step. Do not edit this file by hand, as your edits will be overwritten by the next Docs build.
		- name: dry-gen verbs
		  href: index.md
		- name: csharp-from-json-schema
		  href: csharp-from-json-schema.md
		- name: mermaid-c4component-diagram-from-dotnet-deps-json
		  href: mermaid-c4component-diagram-from-dotnet-deps-json.md
		- name: mermaid-class-diagram-from-csharp
		  href: mermaid-class-diagram-from-csharp.md
		- name: mermaid-class-diagram-from-json-schema
		  href: mermaid-class-diagram-from-json-schema.md
		- name: mermaid-er-diagram-from-csharp
		  href: mermaid-er-diagram-from-csharp.md
		- name: mermaid-er-diagram-from-efcore
		  href: mermaid-er-diagram-from-efcore.md
		- name: mermaid-er-diagram-from-json-schema
		  href: mermaid-er-diagram-from-json-schema.md
		- name: options-from-commandline
		  href: options-from-commandline.md
		- name: verbs-from-options-file
		  href: verbs-from-options-file.md
		
		"""

Scenario: Should generate verb markdown for options-from-commandline
	When I generate the docs markdown for the verb "options-from-commandline"
	Then console out should contain the text
		"""
		---
		# Autogenerated by the Docs build step. Do not edit this file by hand, as your edits will be overwritten by the next Docs build.
		layout: page
		title: options-from-commandline
		description: Details about the dry-gen verb options-from-commandline
		show_sidebar: false
		menubar: verbs_menu
		hero_height: is-fullwidth
		---
		Generate dry-gen options for a verb from the command line. 
		
		## Options
		The verb 'options-from-commandline' uses the following options.
		
		|Option|Alias|Type|Description|
		|---|---|---|---|
		|--options-file|-f|string|Read options from this file.|
		|--output-file|-o|string|Write the generated representation to this file.|
		|--replace-token-in-output-file||string|Replace this token in the output file with the generated representation instead of just writing the generated representation to the specified output file.|
		|--verb||string|The dryg-gen verb to generate options for.|
		
		{% include notification.html status="is-dark" 
		message="You can always get information about this verb's options by running the command 
		
		`dry-gen options-from-commandline --help`."
		%}
		## Options file template
		Here is a template for an options file for 'options-from-commandline'. 
		```
		#
		# dry-gen options for verb 'options-from-commandline'
		#
		#output-file: string
		#replace-token-in-output-file: string
		#verb: string
		```
		{% include notification.html status="is-dark" 
		message="You can generate the same template your self with the command 
		
		`dry-gen options-from-commandline --verb options-from-commandline`"
		%}
		
		"""

# We could test for the docs generation for more verbs, but that would only make more fragile test, since the docs changes each time the help text for a verb is improved...