using DryGen.Features.VerbsFromOptionsFile;

namespace DryGen.Features.Mermaid.FromJsonSchema.ClassDiagram;

public class MermaidClassDiagramFromJsonSchemaConfiguration : VerbsFromOptionsFileConfiguration<MermaidClassDiagramFromJsonSchemaOptions>
{
}