# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", '~> 4.3.2'
gem "bulma-clean-theme"

# TODO: How do we get past this one?
#gem 'wdm', '>= 0.1.0' if Gem.win_platform?  
# When running the Guthub action (on ubuntu-latest), gem 'wdm' causes this error:
# You have deleted from the Gemfile:
# * wdm (>= 0.1.0)
# Error: Gemfile.lock probably needs updating. Run "bundle install" locally and commit changes. Exiting action

# This is needed as a work around when Ruby 3.X throws LoadError
# `require': cannot load such file -- webrick
# Ref https://github.com/jekyll/jekyll/issues/8523
gem "webrick"