name: Prepare docs for deployment to Github Pages

on:
  push:
    branches:
      - main 

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Jekyll dependencies & build docs
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: ./docs

      - name: Prepare generated docs for deployment on branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
